name: mern-dockerize

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-dockerize
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-dockerize
    command: npm run dev -- --host
    depends_on:
      - api
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-dockerize
    depends_on:
      - api
      - frontend

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  mern-dockerize:
    driver: bridge
